Repository clubgamma/Sudoku, pull requests merged in 2024-10, with the labels that each got.

#8 fixes #5: Grid-Based Sudoku Board Input
  main.c
Labels: good first issue, Level 1, hacktoberfest-accepted

#9 fixes #3: Step counter for solving the Sudoku
  main.c
  sudoku.c
  sudoku.h
Labels: Level 1

#11 Added support for .txt files
  .gitignore
  EXAMPLE/puz.txt
  README.md
  main.c
Labels: Level 3, Hacktoberfest2024

#13 Integrated Error Detection
  main.c
  sudoku.c
  sudoku.h
Labels: Level 1, hacktoberfest-accepted

#15 #12 Optimized algorithm
  main.c
  sudoku.c
  sudoku.h
Labels: Level 2, hacktoberfest-accepted

#17 fixes #10: Add Puzzle Difficulty Classification
  main.c
  sudoku.c
  sudoku.h
Labels: Level 2, hacktoberfest-accepted

#24 update Input validation
  main.c
  sudoku.c
Labels: good first issue, Level 1, hacktoberfest-accepted

#25 Read Size of grid from file..
  main.c
Labels: bug, hacktoberfest-accepted

#27 Restart the game..
  main.c
Labels: Level 1, hacktoberfest-accepted

#28 Complete GUI Based Sudoku
  Makefile
  main.c
  src/core/sudoku.c
  src/core/sudoku.h
  src/core/sudoku.o
  src/gui/main.c
  src/gui/main.o
  src/gui/sudoku_gui.c
  src/gui/sudoku_gui.h
  src/gui/sudoku_gui.o
Labels: Level 3, hacktoberfest-accepted

#29 Optimized the SolveSudoku function
  .gitignore
  main.c
  src/core/sudoku.c
  src/core/sudoku.h
  src/core/sudoku.o
  src/gui/main.o
  src/gui/sudoku_gui.c
  src/gui/sudoku_gui.o
Labels: Level 1, hacktoberfest-accepted
